name: Test Project
on: 
  push:
    branches:
      - 'gihubactions'
  workflow_dispatch: 
    branches:
      - 'gihubactions'
env:
  NODE_ENV: dev
  PORT: 5000
  JWT_EXPIRES_IN: 24h
  APP_VERSION: v1.1.1
  APP_ORIGIN: http://localhost
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci 
      - name: Run tests
        run: npm run test
  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Run test coverage
        run: npm run coverage
  deploy: 
    needs: [test, coverage]
    runs-on: ubuntu-latest
    steps:  
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying on server -dockerhub or AWS or K8s"
